### PR TITLE
Bump binary upper bound

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
A release would also be greated appreciated.

**Comment by ivarnymoen** [comment]
I think I pushed a new release to Hackage along with merging this commit, but I might have messed up somewhere.

Either way, the project could use some upkeep that I'm not really up for. I noticed one test is failing for me, the tests are probably a bit nonsensical in the first place and not all all multi threaded IIRC. The bench suite is probably not that meaningful either.

The library could also use a rewrite to get rid of thrown exceptions in favor of something Either-like..

If willing, you'd be more than welcome to take over as the official maintainer. It's been ages since I actually compiled this thing myself. Not that you'd have to put in a lot of work. Just bumping dependencies when necessary is more than I've been doing.

**Comment by bgamari** [comment]
Sure, I would be happy to take it over. Feel free to transfer the GitHub project to me and grant `BenGamari` Maintainership on Hackage.

**Comment by ivarnymoen** [comment]
Seems you need to delete (or rename?) your fork before I can transfer the project.

**Comment by bgamari** [comment]
Ivar Nymoen <notifications@github.com> writes:

> Seems you need to delete (or rename?) your fork before I can transfer the project.

Done.

**Pull request merged**
